# Generated by Django 5.2.4 on 2025-08-02 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='tittle',
            new_name='title',
        ),
    ]
